"""
test_export_html.py — The ink & vermilion HTML report.

Single file, zero external resources, colors only through the CSS
variables generated by theme.py (light on :root, dark under
prefers-color-scheme), story lead and clean summary when present, and
Review Focus 4: data-derived strings such as "<b>y</b>" are escaped.
"""

from __future__ import annotations

import re
from datetime import datetime

import pytest

from datadelta         import __version__, theme
from datadelta.differ  import DiffResult, Finding
from datadelta.export  import export_html


NOW = datetime(2026, 10, 1, 14, 2)


def _result(*findings: Finding, before: int = 1000, after: int = 744, cleaning: dict | None = None) -> DiffResult:
    result = DiffResult(
        rows_before   = before,
        rows_after    = after,
        row_delta     = after - before,
        row_delta_pct = (after - before) / max(before, 1),
        findings      = list(findings),
        scenario      = "etl",
    )
    result.cleaning = cleaning
    return result


def _html(tmp_path, result: DiffResult, **kwargs) -> str:
    out = tmp_path / "report.html"
    export_html(result, out, now=NOW, **kwargs)
    return out.read_text(encoding="utf-8")


def _style(html: str) -> str:
    return html.split("<style>", 1)[1].split("</style>", 1)[0]


FAIL_KEYS = Finding("integrity",    "order_id", "FAIL", "256 key(s) deleted from 'order_id' (25.6% of original)",
                    "Keys present in before but not in after.", {})
WARN_GONE = Finding("distribution", "region",   "WARN", "Categories disappeared from 'region': ['APAC']", "", {})
INFO_NULL = Finding("distribution", "地区",      "INFO", "Null rate increased: '地区' (0.0% → 5.0%)", "", {})
CLEAN     = Finding("clean",        "amount",   "INFO", "before · amount · 40 values parsed as numbers", "", {})
KPI       = Finding("custom",       None,       "PASS", "on_time_rate: 0.97 → 0.96", "", {})
HTML_COL  = Finding("schema",       "<b>y</b>", "WARN", "Column added: '<b>y</b>' (type: str)",
                    "Column <b>y</b> exists only in after.", {})


def _cleaning() -> dict:
    def report(rows_before: int, rows_after: int, cells: int, retyped: dict) -> dict:
        return {
            "stats": {
                "rows_before": rows_before, "rows_after": rows_after, "cells_changed": cells,
                "columns_retyped": retyped, "nulls_before": {}, "nulls_after": {},
                "duplicate_rows": 0, "duplicate_keys": None,
            },
            "actions": [{"step": "numbers", "column": "amount", "action": "parsed_number",
                         "count": cells, "note": "", "examples": [["$1,200.50", 1200.5]]}],
        }
    return {
        "before": report(1000, 1000, 1200, {"amount": "number", "<b>y</b>": "date"}),
        "after":  report(750, 744, 893, {"amount": "number"}),
    }


# ── Self-contained ────────────────────────────────────────────────────────────

def test_no_external_resources(tmp_path):
    html = _html(tmp_path, _result(FAIL_KEYS, WARN_GONE, CLEAN, KPI, cleaning=_cleaning()), story="A short story.")
    assert "http://" not in html
    assert "https://" not in html
    assert "<script" not in html
    assert "<link" not in html
    assert "@import" not in html
    assert "url(" not in html


# ── Palette and typography from theme.py ─────────────────────────────────────

def test_css_variables_for_light_and_dark(tmp_path):
    style = _style(_html(tmp_path, _result(FAIL_KEYS)))
    light = theme.css_variables("light")
    dark  = theme.css_variables("dark")
    assert light in style
    assert dark in style
    assert "prefers-color-scheme: dark" in style
    assert style.index(":root {") < style.index(light) < style.index("prefers-color-scheme: dark") < style.index(dark)


def test_no_color_literal_outside_the_variable_blocks(tmp_path):
    style = _style(_html(tmp_path, _result(FAIL_KEYS)))
    for mode in ("light", "dark"):
        style = style.replace(theme.css_variables(mode), "")
    assert re.search(r"#[0-9A-Fa-f]{3,8}\b", style) is None
    assert "rgb(" not in style
    for token in ("paper", "ink", "muted", "rule", "vermilion", "ochre", "sage"):
        assert f"var(--{token})" in style


def test_fonts_layout_and_tabular_figures(tmp_path):
    style = _style(_html(tmp_path, _result(FAIL_KEYS)))
    assert theme.FONT_SERIF in style                    # quotes not HTML-escaped inside <style>
    assert theme.FONT_SANS in style
    assert theme.FONT_MONO in style
    assert "max-width: 760px" in style
    assert "font-variant-numeric: tabular-nums" in style
    assert "&#34;" not in style


# ── Structure ─────────────────────────────────────────────────────────────────

def test_masthead_verdict_and_counts(tmp_path):
    html = _html(tmp_path, _result(FAIL_KEYS, WARN_GONE, INFO_NULL))
    assert '<span class="wordmark">data <span class="mark">▲</span></span>' in html
    assert '<span class="scenario">ETL Validation</span>' in html
    assert "Generated 2026-10-01 14:02" in html
    assert '<p class="verdict sev-FAIL"><span class="glyph">▲</span> fail</p>' in html
    assert '<p class="counts">1 fail · 1 warn · 1 info</p>' in html


def test_pass_verdict(tmp_path):
    html = _html(tmp_path, _result(before=10, after=10))
    assert '<p class="verdict sev-PASS"><span class="glyph">○</span> pass</p>' in html
    assert '<span class="delta">unchanged</span>' in html


def test_rows_summary(tmp_path):
    html = _html(tmp_path, _result(FAIL_KEYS))
    assert '<span class="label">rows</span>1,000 → 744' in html
    assert '<span class="delta">▼ 256 · −25.6%</span>' in html


def test_layers_in_order_with_glyph_word_title_detail(tmp_path):
    html = _html(tmp_path, _result(KPI, INFO_NULL, WARN_GONE, FAIL_KEYS, CLEAN, HTML_COL))
    positions = [html.index(f"<h2>{title}</h2>") for title in
                 ("clean", "schema", "integrity", "distribution", "custom metrics")]
    assert positions == sorted(positions)
    assert '<li class="finding sev-FAIL">' in html
    assert '<span class="word">fail</span>' in html
    assert '<span class="title">256 key(s) deleted from &#39;order_id&#39; (25.6% of original)</span>' in html
    assert '<span class="detail">Keys present in before but not in after.</span>' in html
    assert "地区" in html                                # UTF-8, not escaped


def test_schema_pass_line_and_empty_layers(tmp_path):
    html = _html(tmp_path, _result(FAIL_KEYS))
    assert '<span class="title">no schema changes</span>' in html
    assert "<h2>clean</h2>" not in html
    assert "<h2>distribution</h2>" not in html
    assert "<h2>custom metrics</h2>" not in html


# ── Story lead ────────────────────────────────────────────────────────────────

def test_story_lead_is_rendered_and_escaped(tmp_path):
    html = _html(tmp_path, _result(FAIL_KEYS), story="Thirty keys <b>vanished</b>.\n\nCheck the loader.")
    assert '<p class="lead">Thirty keys &lt;b&gt;vanished&lt;/b&gt;.\n\nCheck the loader.</p>' in html
    assert html.index('class="verdict') < html.index('class="lead"') < html.index('class="rows"')


def test_no_lead_without_story(tmp_path):
    assert 'class="lead"' not in _html(tmp_path, _result(FAIL_KEYS))


# ── Clean summary ─────────────────────────────────────────────────────────────

def test_clean_summary_when_cleaning_is_present(tmp_path):
    html = _html(tmp_path, _result(CLEAN, FAIL_KEYS, cleaning=_cleaning()))
    block = html.split('<section class="clean-summary">', 1)[1].split("</section>", 1)[0]
    rows = re.findall(r"<tr>\s*<td>(\w+)</td>\s*<td class=\"num\">([\d,]+)</td>\s*<td class=\"num\">([\d,]+)</td>", block)
    assert rows == [("before", "1,200", "0"), ("after", "893", "6")]
    assert "amount → number, &lt;b&gt;y&lt;/b&gt; → date" in block
    assert "$1,200.50" not in html                      # examples stay out of the summary
    assert html.index("<h2>integrity</h2>") < html.index('<section class="clean-summary">') < html.index("<footer>")


def test_no_clean_summary_without_cleaning(tmp_path):
    assert "clean-summary" not in _html(tmp_path, _result(FAIL_KEYS))


# ── Review Focus 4: escaping ──────────────────────────────────────────────────

def test_html_in_column_names_is_escaped(tmp_path):
    html = _html(tmp_path, _result(HTML_COL))
    assert "<b>y</b>" not in html
    assert "Column added: &#39;&lt;b&gt;y&lt;/b&gt;&#39; (type: str)" in html
    assert "Column &lt;b&gt;y&lt;/b&gt; exists only in after." in html


def test_scenario_name_is_escaped(tmp_path):
    result = _result(FAIL_KEYS)
    result.scenario = "<i>custom</i>"
    html = _html(tmp_path, result)
    assert "<i>custom</i>" not in html
    assert '<span class="scenario">&lt;i&gt;custom&lt;/i&gt;</span>' in html


# ── Footer ────────────────────────────────────────────────────────────────────

def test_footer_has_the_version(tmp_path):
    html = _html(tmp_path, _result(FAIL_KEYS))
    assert f"<footer>Generated by data ▲ datadelta v{__version__}</footer>" in html


# ── CLI ───────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("mode", [[], ["--json"]])
def test_cli_export_writes_the_new_design(cli, etl_pair, tmp_path, mode):
    before, after = etl_pair
    out = tmp_path / "report.html"
    result = cli("diff", before, after, *mode, "--export", out)
    assert result.exit_code == 1
    html = out.read_text(encoding="utf-8")
    assert "prefers-color-scheme: dark" in html
    assert '<p class="verdict sev-FAIL">' in html
    assert "key(s) deleted from &#39;order_id&#39;" in html
