"""
test_export_escape.py — Every data-derived string in the HTML report is
escaped, and the footer reports the real package version.
"""

from __future__ import annotations

from datetime import datetime

from datadelta         import __version__
from datadelta.differ  import DiffResult, Finding
from datadelta.export  import export_html


PAYLOAD = "<script>alert(1)</script>"


def _result(scenario: str = "general") -> DiffResult:
    return DiffResult(
        rows_before   = 10,
        rows_after    = 9,
        row_delta     = -1,
        row_delta_pct = -0.1,
        findings      = [
            Finding(
                layer    = "distribution",
                column   = PAYLOAD,
                severity = "WARN",
                title    = f"Categories disappeared from {PAYLOAD}: [{PAYLOAD}]",
                detail   = f"Column {PAYLOAD} lost a category.",
                metric   = {"missing_values": [PAYLOAD]},
            ),
        ],
        scenario      = scenario,
    )


def _render(tmp_path, result: DiffResult, **kwargs) -> str:
    out = tmp_path / "report.html"
    export_html(result, out, **kwargs)
    return out.read_text(encoding="utf-8")


def test_finding_title_and_detail_are_escaped(tmp_path):
    html = _render(tmp_path, _result())
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in html
    assert "<script>alert" not in html


def test_scenario_name_is_escaped(tmp_path):
    html = _render(tmp_path, _result(scenario=PAYLOAD))
    assert "<title>datadelta · &lt;script&gt;" in html
    assert "<script>alert" not in html


def test_story_text_is_escaped(tmp_path):
    html = _render(tmp_path, _result(), story="<img src=x onerror=alert(1)>")
    assert "&lt;img src=x onerror=alert(1)&gt;" in html
    assert "<img" not in html


def test_footer_uses_package_version(tmp_path):
    html = _render(tmp_path, _result())
    assert f"Generated by data ▲ datadelta v{__version__}" in html
    assert "v0.2.0" not in html


def test_timestamp_can_be_pinned(tmp_path):
    html = _render(tmp_path, _result(), now=datetime(2026, 10, 1, 14, 2))
    assert "Generated 2026-10-01 14:02" in html
