"""
export.py — Generate a self-contained HTML report (--export flag).

The output is a single .html file with no external dependencies: all CSS
is inlined, no web fonts, no CDN links, no JavaScript. It opens anywhere
(email, Slack, a GitHub PR) and loads nothing from the network.

DESIGN (ink & vermilion)
  One narrow column (max-width 760px) on paper, ink text, 1px rules:
    wordmark "data ▲" + scenario + time
    → verdict (glyph + word in the severity color, plus counts)
    → story lead in a larger serif (with --story)
    → rows summary (tabular figures)
    → findings by layer: clean, schema, integrity, distribution, custom
    → clean summary per side (with --clean)
    → footer with the package version
  Colors are CSS custom properties generated by theme.css_variables():
  light on :root, dark under @media (prefers-color-scheme: dark). Fonts
  are the local stacks from theme.py. No color literal lives here.

WHY AUTOESCAPE?
  Almost every string in the report is derived from the data: column
  names, category values, finding titles, the scenario name, and the
  LLM-written story. A column literally named "<script>...</script>"
  must show up as text, not run as code when a colleague opens the
  file. The template is therefore compiled from an Environment with
  autoescape=True, which HTML-escapes every {{ ... }} expression. The
  only values marked |safe are the CSS variables and font stacks, which
  are constants from theme.py.

The version in the footer comes from datadelta.__version__, the
package's single version source.
"""

from __future__ import annotations

import math
from datetime import datetime
from pathlib  import Path

from jinja2 import Environment

from .        import __version__, theme
from .differ  import DiffResult, Finding


# Layers in display order, and their (lowercase) section titles.
LAYERS: tuple[str, ...] = ("clean", "schema", "integrity", "distribution", "custom")
LAYER_TITLES: dict[str, str] = {
    "clean":        "clean",
    "schema":       "schema",
    "integrity":    "integrity",
    "distribution": "distribution",
    "custom":       "custom metrics",
}


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="color-scheme" content="light dark">
<title>datadelta · {{ scenario_label }}</title>
<style>
  /* Palette from datadelta.theme (css_variables) */
  :root {
  {{ css_light|safe }}
  }
  @media (prefers-color-scheme: dark) {
    :root {
  {{ css_dark|safe }}
    }
  }

  * { box-sizing: border-box; margin: 0; padding: 0; }
  html { background: var(--paper); }
  body {
    background: var(--paper);
    color: var(--ink);
    font-family: {{ font_sans|safe }};
    font-size: 15px;
    line-height: 1.55;
    max-width: 760px;
    margin: 0 auto;
    padding: 56px 24px 80px;
  }
  .num, .rows, .counts, .meta, .word {
    font-family: {{ font_mono|safe }};
    font-variant-numeric: tabular-nums;
  }

  /* ── Masthead ───────────────────────────────────────────────────────── */
  .masthead {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: baseline;
    gap: 8px 24px;
    padding-bottom: 14px;
    border-bottom: 1px solid var(--rule);
  }
  .wordmark { font-family: {{ font_serif|safe }}; font-size: 22px; font-weight: 600; }
  .mark     { color: var(--vermilion); }
  .scenario { color: var(--muted); margin-left: 14px; }
  .meta     { color: var(--muted); font-size: 13px; }

  /* ── Verdict and story lead ─────────────────────────────────────────── */
  .verdict { margin-top: 44px; font-family: {{ font_serif|safe }}; font-size: 34px; line-height: 1.2; }
  .counts  { margin-top: 6px; color: var(--muted); font-size: 13px; }
  .lead {
    margin-top: 28px;
    font-family: {{ font_serif|safe }};
    font-size: 20px;
    line-height: 1.6;
    white-space: pre-line;
    overflow-wrap: anywhere;
  }

  /* ── Severity colors: glyph and word, never color alone ─────────────── */
  .sev-FAIL .glyph, .sev-FAIL .word, .verdict.sev-FAIL { color: var(--vermilion); }
  .sev-WARN .glyph, .sev-WARN .word, .verdict.sev-WARN { color: var(--ochre); }
  .sev-INFO .glyph, .sev-INFO .word, .verdict.sev-INFO { color: var(--muted); }
  .sev-PASS .glyph, .sev-PASS .word, .verdict.sev-PASS { color: var(--sage); }

  /* ── Rows summary ───────────────────────────────────────────────────── */
  .rows {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    gap: 4px 24px;
    margin-top: 36px;
    padding: 12px 0;
    border-top: 1px solid var(--rule);
    border-bottom: 1px solid var(--rule);
    font-size: 14px;
  }
  .label { color: var(--muted); margin-right: 16px; }
  .delta { color: var(--muted); }

  /* ── Findings ───────────────────────────────────────────────────────── */
  section { margin-top: 40px; }
  h2 {
    font-size: 12px;
    font-weight: 600;
    letter-spacing: 0.08em;
    color: var(--muted);
    padding-bottom: 8px;
    border-bottom: 1px solid var(--rule);
  }
  ul.findings { list-style: none; }
  li.finding {
    display: grid;
    grid-template-columns: 1.4em 3.4em 1fr;
    column-gap: 8px;
    padding: 10px 0;
    border-bottom: 1px solid var(--rule);
  }
  .word   { font-size: 13px; padding-top: 2px; }
  .title  { overflow-wrap: anywhere; }
  .detail {
    grid-column: 3;
    color: var(--muted);
    font-size: 13px;
    white-space: pre-line;
    overflow-wrap: anywhere;
    margin-top: 2px;
  }

  /* ── Clean summary ──────────────────────────────────────────────────── */
  table.clean { width: 100%; border-collapse: collapse; font-size: 14px; }
  table.clean th {
    text-align: left;
    font-weight: 400;
    font-size: 12px;
    color: var(--muted);
    padding: 8px 0;
    border-bottom: 1px solid var(--rule);
  }
  table.clean td { padding: 8px 0; border-bottom: 1px solid var(--rule); vertical-align: top; overflow-wrap: anywhere; }
  table.clean .num { text-align: right; padding-right: 24px; white-space: nowrap; }

  /* ── Footer ─────────────────────────────────────────────────────────── */
  footer {
    margin-top: 56px;
    padding-top: 14px;
    border-top: 1px solid var(--rule);
    color: var(--muted);
    font-size: 12px;
  }

  @media (max-width: 520px) {
    body     { padding: 32px 16px 56px; }
    .verdict { font-size: 28px; }
    .lead    { font-size: 18px; }
  }
</style>
</head>
<body>

<header class="masthead">
  <div>
    <span class="wordmark">{{ brand_word }} <span class="mark">{{ brand_mark }}</span></span>
    <span class="scenario">{{ scenario_label }}</span>
  </div>
  <div class="meta">Generated {{ timestamp }}</div>
</header>

<p class="verdict sev-{{ verdict.severity }}"><span class="glyph">{{ verdict.glyph }}</span> {{ verdict.word }}</p>
<p class="counts">{{ counts.FAIL }} fail · {{ counts.WARN }} warn · {{ counts.INFO }} info</p>

{% if story %}
<p class="lead">{{ story }}</p>
{% endif %}

<div class="rows">
  <span><span class="label">rows</span>{{ rows.before }} → {{ rows.after }}</span>
  <span class="delta">{{ rows.delta }}</span>
</div>

{% for layer in layers %}
<section class="layer layer-{{ layer.key }}">
  <h2>{{ layer.title }}</h2>
  <ul class="findings">
    {% for f in layer.findings %}
    <li class="finding sev-{{ f.severity }}">
      <span class="glyph">{{ f.glyph }}</span>
      <span class="word">{{ f.word }}</span>
      <span class="title">{{ f.title }}</span>
      {% if f.detail %}<span class="detail">{{ f.detail }}</span>{% endif %}
    </li>
    {% endfor %}
  </ul>
</section>
{% endfor %}

{% if cleaning %}
<section class="clean-summary">
  <h2>clean summary</h2>
  <table class="clean">
    <thead>
      <tr><th>side</th><th class="num">cells changed</th><th class="num">rows dropped</th><th>columns retyped</th></tr>
    </thead>
    <tbody>
      {% for side in cleaning %}
      <tr>
        <td>{{ side.side }}</td>
        <td class="num">{{ side.cells_changed }}</td>
        <td class="num">{{ side.rows_dropped }}</td>
        <td>{{ side.retyped }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>
{% endif %}

<footer>Generated by data ▲ datadelta v{{ version }}</footer>
</body>
</html>
"""


# Compiled once at import time; autoescape=True escapes every {{ ... }}.
_ENV      = Environment(autoescape=True)
_TEMPLATE = _ENV.from_string(HTML_TEMPLATE)


def export_html(
    result:      DiffResult,
    output_path: Path,
    *,
    story:       str | None      = None,
    now:         datetime | None = None,
) -> None:
    """
    Render the HTML template and write it to disk.

    story: optional narrative text (from --story) shown as the lead.
    now:   timestamp shown in the header; defaults to the current time
           (tests pass a fixed value).
    """
    from .scenarios import SCENARIO_LABELS

    brand_word, brand_mark = theme.BRAND.rsplit(" ", 1)
    severity = result.summary_severity

    html = _TEMPLATE.render(
        scenario_label = SCENARIO_LABELS.get(result.scenario, result.scenario),
        timestamp      = (now or datetime.now()).strftime("%Y-%m-%d %H:%M"),
        css_light      = theme.css_variables("light"),
        css_dark       = theme.css_variables("dark"),
        font_serif     = theme.FONT_SERIF,
        font_sans      = theme.FONT_SANS,
        font_mono      = theme.FONT_MONO,
        brand_word     = brand_word,
        brand_mark     = brand_mark,
        verdict        = _severity_view(severity),
        counts         = {s: sum(1 for f in result.findings if f.severity == s) for s in ("FAIL", "WARN", "INFO")},
        story          = story.strip() if story else None,
        rows           = _rows_view(result.rows_before, result.rows_after),
        layers         = _layers_view(result.findings),
        cleaning       = _cleaning_view(result.cleaning),
        version        = __version__,
    )

    Path(output_path).write_text(html, encoding="utf-8")


# ─────────────────────────────────────────────────────────────────────────────
# View models — plain dicts, so the template only formats and escapes
# ─────────────────────────────────────────────────────────────────────────────

def _severity_view(severity: str) -> dict:
    return {
        "severity": severity,
        "glyph":    theme.SEVERITY_GLYPH[severity],
        "word":     theme.SEVERITY_WORD[severity],
    }


def _finding_view(finding: Finding) -> dict:
    return {**_severity_view(finding.severity), "title": finding.title, "detail": finding.detail}


def _layers_view(findings: list[Finding]) -> list[dict]:
    """Non-empty layers in display order; schema always (a pass line when unchanged)."""
    layers = []
    for key in LAYERS:
        items = [_finding_view(f) for f in findings if f.layer == key]
        if not items and key == "schema":
            items = [{**_severity_view("PASS"), "title": "no schema changes", "detail": ""}]
        if items:
            layers.append({"key": key, "title": LAYER_TITLES[key], "findings": items})
    return layers


def _rows_view(before: int, after: int) -> dict:
    """Row counts and the change: "▼ 256 · −25.6%", "▲ 12 · +1.2%" or "unchanged"."""
    delta = after - before
    if delta == 0:
        text = "unchanged"
    else:
        glyph = theme.DELTA_UP if delta > 0 else theme.DELTA_DOWN
        text  = f"{glyph} {abs(delta):,}"
        pct   = delta / before if before else math.nan
        if math.isfinite(pct):
            sign = "+" if delta > 0 else theme.MINUS
            text += f" {theme.SEP} {sign}{abs(pct):.1%}"
    return {"before": f"{before:,}", "after": f"{after:,}", "delta": text}


def _cleaning_view(cleaning: dict | None) -> list[dict]:
    """One row per cleaned side: cells changed, rows dropped, retyped columns."""
    if not cleaning:
        return []
    sides = []
    for side in ("before", "after"):
        report = cleaning.get(side)
        if report is None:
            continue
        stats   = report["stats"]
        retyped = ", ".join(f"{col} {theme.ARROW} {kind}" for col, kind in stats["columns_retyped"].items())
        sides.append({
            "side":          side,
            "cells_changed": f"{stats['cells_changed']:,}",
            "rows_dropped":  f"{stats['rows_before'] - stats['rows_after']:,}",
            "retyped":       retyped or "none",
        })
    return sides
